name: financier_frontend
description: "Client for Financier application."
publish_to: 'none'

version: 1.0.0+1

# ВАЖНО: Обновляем минимальную версию SDK. Новые пакеты требуют этого.
environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.6
  
  # State Management & DI
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Routing
  go_router: ^14.1.1

  # Networking
  dio: ^5.4.3+1

  # Local Storage
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3

  # Secure Storage for JWT
  flutter_secure_storage: ^9.2.2

  # Models & Serialization
  json_annotation: ^4.9.0

  # Environment Variables
  envied: ^0.5.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.10
  riverpod_generator: ^2.4.0
  go_router_builder: ^2.4.1
  json_serializable: ^6.8.0
  envied_generator: ^0.5.4+1

  # Linting
  flutter_lints: ^4.0.0 # <-- Обновлено до последней мажорной версии
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true