version: '3.8'

services:
  db:
    ports:
      - "5433:5432" # Use a different host port for the test DB
    environment:
      - POSTGRES_DB=${POSTGRES_DB}_test # Use a different database name

  api:
    ports:
      - "8001:8000"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}_test