version: '3.8'

services:
  db_test:
    image: postgres:15-alpine
    container_name: financier_db_test
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${TEST_POSTGRES_DB} # Используем тестовую БД
    ports:
      - "5433:5432" # Другой порт на хосте во избежание конфликтов

  api_test:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: financier_api_test
    # Команда для тестов: сначала миграции, потом запуск pytest
    command: sh -c "alembic upgrade head && pytest"
    volumes:
      - ./backend:/app
    env_file:
      - ./.env
    # Переопределяем переменные для подключения к тестовой БД
    environment:
      - POSTGRES_SERVER=${TEST_POSTGRES_SERVER}
      - POSTGRES_DB=${TEST_POSTGRES_DB}
    depends_on:
      - db_test